main/urls.py
from django.urls import path
from .views import mainapp, refresh_db


app_name = 'main'


urlpatterns = [
    path('', mainapp, name='index'),
    path('refresh/', refresh_db, name='refresh')
]

realtor/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index

urlpatterns = [
    path('main/', include('main.urls', namespace='main')),
    path('admin/', admin.site.urls),
    path('', index, name='index0'),

]

main/models.py
from django.db import models

# Create your models here.


class Announce(models.Model):
    """
    address
    district
    options
    price
    images
    url
    source
    phonenumber
    """
    title = models.CharField(max_length=255, blank=False, verbose_name='Наименование')
    address = models.CharField(max_length=255, blank=False, verbose_name='Адрес')
    district = models.CharField(max_length=120, blank=True, null=True, verbose_name='Район, округ')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена')
    images_path = models.CharField(max_length=1024, blank=True, verbose_name='Путь сохраненных фото')
    url = models.CharField(max_length=1024, blank=True, verbose_name='Ссылка объявления')
    #published_date = models.DateTimeField(verbose_name='Дата публикации на сайте')
    write_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    update_date = models.DateTimeField(auto_now=True, verbose_name='Дата изменения')
    source = models.CharField(max_length=120, blank=False, verbose_name='Ресурс объявлсения')

    class Meta:
        verbose_name = 'Объявление'
        verbose_name_plural = 'Объявления'


class Options(models.Model):
    """
    type
    kind
    rooms
    floor
    square
    buildings_material
    """
    pass

weather/models.py
from django.db import models

# Create your models here.

main/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from .models import Announce
from .services.avito import get_page_content
# Create your views here.


def mainapp(request):
    all_ad = Announce.objects.all()
    context = {
        'ads': all_ad,
    }
    return render(request, 'index.html', context)


def refresh_db(request):
    get_page_content()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

realtor/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'main_index.html')

weather/views.py
from django.shortcuts import render

# Create your views here.

main/templates/index.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Список объявлений</title>
</head>
<body>
<header>
    <a href="{% url 'main:refresh' %}">Обновить</a>
</header>
<ul>
    {% for ad in ads %}
    <li>
        <h3>{{ ad.title }}</h3>
        <p>{{ ad.address }}</p>
        <p>{{ ad.district }}</p>
        <p>{{ ad.price }}</p>

    </li>
    {% endfor %}
</ul>
</body>
</html>

templates/main_index.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Главная</title>
</head>
<body>
<ul>
    <li><a href="{% url 'index0' %}">Главная</a></li>
    <li><a href="{% url 'main:index' %}">Список объявлений Авито</a></li>
    <li><a href="/admin/">Админка</a></li>
</ul>
</body>
</html>